### PR TITLE
Add optional routes for top-level files

### PR DESCRIPTION
**Pull request by xdissent**
For robots, favicon etc

### CODE REVIEW

**Comment by sdd** [comment]
Hi @xdissent, another nice PR, thanks! Would you also be able to include a short note regarding usage to the readme? Feel free to add an @mention of yourself as a contributor too if you like.

Once this change and the one in the other PR is in place, I'll publish to npm.

Cheers!

**Comment by xdissent** [comment]
There ya go. Also added one tiny fix to exclude `index.html` from the list of top-level files, bc that's redundant, and made `topFiles` ignore `dotFiles` if set. I included a note about `dotFiles` in the README since that already got merged!

**Comment by dzimine** [comment]
Please merge: to me this PR & #8 makes apig-s3 brings what I need (currently using @xdissent branch).

**Comment by sdd** [comment]
Published with v1.2 (https://www.npmjs.com/package/serverless-apig-s3)

**Pull request merged**
