### PR TITLE
Allow custom s3 asset resource path prefix

### PR DESCRIPTION
**Pull request by xdissent**

### CODE REVIEW

**Comment by sdd** [comment]
Hi Greg,

Thanks a lot for the PR. Would it be possible if you could also add a note at the bottom of the readme to describe this option?

Thanks for your contribution!

**Comment by xdissent** [comment]
How's that? Also added note for `resourceName`

**Comment by sdd** [comment]
Sorry for the delayed merge. Thanks Greg

**Comment by sdd** [comment]
Published with v1.2 (https://www.npmjs.com/package/serverless-apig-s3)

**Pull request merged**
